<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://rest.soa.insa.fr" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://rest.soa.insa.fr" xmlns:intf="http://rest.soa.insa.fr" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://rest.soa.insa.fr" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="getLongueur">
    <complexType/>
   </element>
   <element name="getLongueurResponse">
    <complexType>
     <sequence>
      <element name="getLongueurReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="getLongueurResponse">

      <wsdl:part element="impl:getLongueurResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="getLongueurRequest">

      <wsdl:part element="impl:getLongueur" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="Comparator">

      <wsdl:operation name="getLongueur">

         <wsdl:input message="impl:getLongueurRequest" name="getLongueurRequest">

       </wsdl:input>

         <wsdl:output message="impl:getLongueurResponse" name="getLongueurResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="ComparatorSoapBinding" type="impl:Comparator">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="getLongueur">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="getLongueurRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="getLongueurResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="ComparatorService">

      <wsdl:port binding="impl:ComparatorSoapBinding" name="Comparator">

         <wsdlsoap:address location="http://localhost:8080/RestWS/services/Comparator"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
